### ISSUE TITLE
There are two appointments but this person managed to answer nps. That means he received nps notificaitoin although it's his second time.

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#106]
Akira has posted an issue in Discord

There are two appointments but this person managed to answer nps. That means he received nps notificaitoin although it's his second time.

**Comment by castilloglenn** [comment]
Discussion: https://discord.com/channels/1161110836635508778/1176408561379725372/1245550179864547442

**Comment by castilloglenn** [comment]
appointment id: 3cd66cb1-ae82-4ff5-8c47-326cec591843

**Comment by Grrom** [comment]
I've found the reason.

![image](https://github.com/umed-jp/umed/assets/62323308/4cd33e36-bfff-4b76-9ecf-b3ac4477356e)

in the past we didn't have patientId in the encounter data and since the service is querying the oldest encounter based on patientId, the service doesn't know that the patient has has a appointment in the past.
![image](https://github.com/umed-jp/umed/assets/62323308/c23d35c0-6836-4bff-88af-6025e37c916a)


the patient Id was only added 5 months ago in this PR
- https://github.com/umed-jp/kitsune-backend/pull/395
![image](https://github.com/umed-jp/umed/assets/62323308/04f7c5c6-90a9-41db-862b-d7dac764155c)

so patients who are having an appointment for the first time in the past 5 months but had a appointment 5 months ago will still receive the nps request notification.

**Comment by Grrom** [comment]
this can be solved by fetching from the fhir to check if the patient has a previous appointment.

**Comment by Grrom** [comment]
fixed
- https://github.com/umed-jp/notification-publisher/pull/60
