### ISSUE TITLE
It creates duplicate pubsub topic when the infra pipeline runs

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#121]
**Describe the bug**
when infra pipeline runs, the fhir notification topic is duplicated.
this causes any feature that relies on fhir notification from pubsub to get duplicated as well, one example is 
- https://github.com/umed-jp/umed/issues/120

**Comment by Grrom** [comment]
when infra runs and there's no existing topic:
- one topic exists

when infra runs and there's an existing topic from previous run:
- one topic exists

when infra runs and there's an existing topic added manually:
- two topics exists

looks like the issue is, infra pipeline doesn't realize that the same topic exists if it's added manually. and it still adds a new topic defined in the code

**Comment by Grrom** [comment]
yup that was it,

I've tested several times,

it seems like we just had to delete the topic that has been added manually

I ran the infra pipeline twice in a row and it didn't duplicate
![image](https://github.com/umed-jp/umed/assets/62323308/f387814d-ecea-4db9-9032-53481d12ddcb)

this is the fhir store, there is only one topic
![image](https://github.com/umed-jp/umed/assets/62323308/76d9f00b-559f-4e62-a5cd-847ea194ad7c)
