### ISSUE TITLE
dispense info missing

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#30]
Raf23 has posted an issue in Discord

dispense info missing

**Comment by castilloglenn** [comment]
fix: https://github.com/umed-jp/practitioner-frontend-ts/pull/408

**Comment by castilloglenn** [comment]
fix is merged

**Comment by castilloglenn** [comment]
here's the fix for it:
- https://github.com/umed-jp/practitioner-frontend-ts/pull/410

**Comment by castilloglenn** [comment]
## Why it happened
The refetching of `getDosageInstructions` of `MedicationSelect` is needed in instantiating the data of a single medication prescription, so when I tried moving it to the top level component, it doesn't trigger the re-fetching anymore when new component is created. Although it fixed the issue where the unit type is disappearing, this issue shows up.

## How to prevent
For now, keep the logic of `MedicationSelect` in it as it is currently working as it is, but if we need to refactor it we need to consider all edge cases for the component.

## How to fix
So I fixed it by reverting the initial PR I created, the solution didn't worked because I didn't think they are going to be related because the data inside `getDosageInstructions` are just static data and doesn't needed to be refetched everytime.

So I created another fix where if the `unit` is not empty, we don't make it empty. A simple and effective solution for it as well. I tested this with the other scenarios and it doesn't produce any other bugs.
