### ISSUE TITLE
🎉  Done The doctor could not see a patient

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#81]
**Describe the bug**
Multiple practitioner roles were created in the process of merging walk-in and schedule, it created the both confusion and technical difficulties seeing a patient

**Comment by akirakakar** [comment]
@Grrom deleted duplicated practitioner role to fix this.

**Comment by Grrom** [comment]
- https://github.com/umed-jp/kitsune-backend/pull/454
was meant to allow multiple roles for one practitioner, which it did.

the fix was, roll back the changes in backend and practitioner-web and delete the new roles that were created.

however, it was deployed prematurely causing the issues.

the correct release should be as written here, in this particular order
- https://github.com/umed-jp/kitsune-remote-config/pull/35

**Comment by rafael-parayno** [comment]
@akirakakar , @Grrom whats left on this??

**Comment by Grrom** [comment]
nothing, I think we can close now
