### ISSUE TITLE
medication request is still duplicated

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#96]
Akira has posted an issue in Discord

medication request is still duplicated

**Comment by Grrom** [comment]
just to add background,

seems like this issue was introduced here
- https://github.com/umed-jp/kitsune-backend/pull/481

In the past when we had this same duplication issue, we introduced some of the code that was removed in the mentioned PR to prevent it, but in this PR, it was removed by accident.

**Comment by rafael-parayno** [comment]
https://github.com/umed-jp/kitsune-backend/pull/493

**Comment by castilloglenn** [comment]
1 week passed and not reported again, will be closing 🙇🏽
